### ISSUE TITLE
Animation not showing up

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/just-your-type#1]
@muxlowc

I removed the excess code I felt like I didn't need from the animation code found on Codepen, and in its preview, it shows the animation as working. When I try to use it in my own code there is no animation shown at all when I open it in my browser. 

**Codepen CSS:**
<img width="795" alt="Screen Shot 2020-03-13 at 10 05 01 PM" src="https://user-images.githubusercontent.com/55240989/76672895-c2fb0b00-6576-11ea-8887-13e09bf114be.png">

**Codepen HTML:**
<img width="795" alt="Screen Shot 2020-03-13 at 10 05 16 PM" src="https://user-images.githubusercontent.com/55240989/76672897-c7272880-6576-11ea-942a-13f591971754.png">

**My CSS:**
<img width="729" alt="Screen Shot 2020-03-13 at 10 06 17 PM" src="https://user-images.githubusercontent.com/55240989/76672904-e45bf700-6576-11ea-8d72-4ff8e6b2905c.png">

**My HTML:**
<img width="730" alt="Screen Shot 2020-03-13 at 10 06 58 PM" src="https://user-images.githubusercontent.com/55240989/76672913-fb024e00-6576-11ea-84d7-9ede14a35034.png">

**Comment by muxlowc** [comment]
@briannaneet Have you pushed your code yet? I am not seeing your index.html or any of your css.. You may need to refork the repository if you didn't fork it properly the first time..

Also, you could add in the stuff you took out for now just so it works, and then I can go through it later and see what we can all subtract :)

If markbot isn;t letting you sibmit, just let me know and I'll give you that mark, and then just post your rationale.

**Comment by briannaneet** [comment]
@muxlowc Sorry about that, I usually don't push until I'm done all my code but I just did it now. I got the animation to work to, I just needed to fix the spacing in the CSS which I did after Markbot pointed it out.

**Comment by briannaneet** [comment]
@muxlowc everything is good on Markbot except I get the error message "There should be 2 Google fonts, both added to the same cart on the Google Fonts website" although I did put them both in the same cart and have them embedded with the same link.

**Comment by muxlowc** [comment]
@briannaneet No worries, I think this might be a glitch with the recent Google Fonts update - I'll go ahead and give you your code mark :)

**Comment by briannaneet** [comment]
@muxlowc alright, thank you!

**Comment by muxlowc** [comment]
@briannaneet can you please close this issue if everything is resolved? Thanks!
